### ISSUE TITLE
@Valid 잘못된 위치

### ISSUE THREAD

**Issue by extremecode716** [depromeet/14th-team5-BE#156]
https://github.com/depromeet/14th-team5-BE/blob/5850a3aca42f073991f9c9573a90b49e2b244deb/member/src/main/java/com/oing/restapi/MemberApi.java#L17

@Valid는 컨트롤러의 클래스나 인터페이스 레벨에 적용하는 것이 아니라, 메소드의 매개변수 레벨에서 사용해야 합니다. 특히, 요청 바디(@RequestBody)를 받는 객체나 @ModelAttribute를 사용하는 객체에 적용하여 그 객체 내부의 필드에 대한 유효성 검증을 활성화하는 데 사용됩니다.

@Validated  의미하는 것 같네요.

**Comment by Ji-soo708** [comment]
이슈 제보해주셔서 감사합니다. `@Valid`가 잘못된 위치에 있는 걸 확인해서 `@Validated`로 바꿔서 핫픽스했습니다! (#163)
