### ISSUE TITLE
스케줄러도 스케일 아웃할 수 있게 스케줄러 Lock 도 적용해보세요.

### ISSUE THREAD

**Issue by extremecode716** [depromeet/14th-team5-BE#158]
https://github.com/depromeet/14th-team5-BE/blob/5850a3aca42f073991f9c9573a90b49e2b244deb/family/src/main/java/com/oing/job/FamilyStatisticJob.java#L16

**Comment by CChuYong** [comment]
https://github.com/depromeet/14th-team5-BE/pull/177 에서 해결되었습니다! 감사합니다!
